name: Code Server with Ngrok v3

on:
  workflow_dispatch:

jobs:
  setup-code-server:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Code Server
      run: |
        curl -fsSL https://code-server.dev/install.sh | sh
        mkdir -p ~/.config/code-server
        echo 'bind-addr: 127.0.0.1:8080' > ~/.config/code-server/config.yaml
        echo 'auth: none' >> ~/.config/code-server/config.yaml

    - name: Install Ngrok v3
      run: |
        curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
        echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
        sudo apt update && sudo apt install ngrok

    - name: Configure Ngrok with static domain
      run: |
        ngrok config add-authtoken 2QQn03lHEv4FSfWroH8VrQt5hAm_3o3Knf2Rc9PjdAG5doJoe
        echo "version: 2" > ngrok.yml
        echo "tunnels:" >> ngrok.yml
        echo "  code-server:" >> ngrok.yml
        echo "    proto: http" >> ngrok.yml
        echo "    addr: 8080" >> ngrok.yml
        echo "    hostname: lynx-singular-loosely.ngrok-free.app" >> ngrok.yml

    - name: Start Code Server and Ngrok
      run: |
        nohup code-server > code-server.log 2>&1 &
        nohup ngrok start --config ngrok.yml --all > ngrok.log 2>&1 &
        echo "Code Server and Ngrok started"

    - name: Keep workflow alive
      run: |
        echo "Keeping workflow alive..."
        while true; do sleep 60; done
