name: VSCode SSH Access via Ngrok

on:
  workflow_dispatch:

jobs:
  ssh-server:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH server
        run: |
          sudo apt update
          sudo apt install -y openssh-server
          sudo systemctl enable ssh
          sudo systemctl start ssh

      - name: Set up SSH user
        run: |
          sudo useradd -m vscode
          echo 'vscode:vscode' | sudo chpasswd
          echo 'vscode ALL=(ALL) NOPASSWD:ALL' | sudo tee /etc/sudoers.d/vscode
          sudo mkdir -p /home/vscode/.ssh
          sudo chmod 700 /home/vscode/.ssh

      - name: Install Ngrok
        run: |
          curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | \
            sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
          echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | \
            sudo tee /etc/apt/sources.list.d/ngrok.list
          sudo apt update
          sudo apt install -y ngrok

      - name: Configure Ngrok with Authtoken
        run: |
          ngrok config add-authtoken 2QQn03lHEv4FSfWroH8VrQt5hAm_3o3Knf2Rc9PjdAG5doJoe

      - name: Start Ngrok tunnel to SSH
        run: |
          ngrok tcp 22 --region=us --remote-addr=lynx-singular-loosely.ngrok-free.app:22 &
          sleep 10
          echo "Ngrok tunnel started. You can now SSH into the runner using your VSCode app."

      - name: Keep runner alive
        run: |
          sleep 3600
